import type {
  EvidencePacket,
  SwarmReceipt,
  SwarmStats,
  PredictionRecord,
  BitLatticeFlow,
  AgentStatus,
  ReplayResult,
} from './vnx-types';

export const MOCK_SWARM_STATS: SwarmStats = {
  total: 42,
  resolved: 38,
  hits: 29,
  accuracy: '76.3%',
};

export const MOCK_PREDICTIONS: PredictionRecord[] = [
  {
    id: 42,
    taskId: 'task-1717081200000-a3f9',
    workerId: 'vnx-trend-001',
    specialty: 'trend',
    prediction: 'up',
    confidence: 0.84,
    score: 12.4,
    timestamp: Date.now() - 120_000,
    receiptHash: 'a1b2c3d4e5f67890',
    direction: 'up',
    priceAtPrediction: 0.1423,
    priceAtResolution: 0.1481,
    hit: true,
    resolved: true,
  },
  {
    id: 41,
    taskId: 'task-1717080900000-b7e1',
    workerId: 'vnx-volatility-003',
    specialty: 'volatility',
    prediction: 'down',
    confidence: 0.71,
    score: 8.9,
    timestamp: Date.now() - 300_000,
    receiptHash: 'b2c3d4e5f6a78901',
    direction: 'down',
    priceAtPrediction: 0.1481,
    priceAtResolution: 0.1455,
    hit: true,
    resolved: true,
  },
  {
    id: 40,
    taskId: 'task-1717080600000-c5d2',
    workerId: 'vnx-sentiment-002',
    specialty: 'sentiment',
    prediction: 'up',
    confidence: 0.62,
    score: 5.1,
    timestamp: Date.now() - 480_000,
    receiptHash: 'c3d4e5f6a7b89012',
    direction: 'up',
    priceAtPrediction: 0.1455,
    priceAtResolution: 0.1420,
    hit: false,
    resolved: true,
  },
];

export const MOCK_EVIDENCE_PACKETS: EvidencePacket[] = [
  {
    id: 'evidence-1717081200123-x7a9',
    version: '1.0',
    createdAt: new Date(Date.now() - 120_000).toISOString(),
    taskHash: 'e3b0c44298fc1c14',
    decisionHash: 'a1b2c3d4e5f67890',
    domain: 'trend',
    task: {
      description: 'Predict HBAR direction next 5min based on EMA crossover and volume profile',
      maxCostHbar: 0.05,
    },
    votes: [
      { worker: 'TrendAnalyzer-1', specialty: 'trend', confidence: 0.84, score: 12.4, evidence: 'EMA(12) crossed above EMA(26) with 2.3x volume confirmation' },
      { worker: 'MomentumBot-3', specialty: 'momentum', confidence: 0.71, score: 9.2, evidence: 'RSI(14) at 58, not overbought, positive divergence on 1m' },
      { worker: 'WhaleWatcher-7', specialty: 'whale', confidence: 0.45, score: 3.1, evidence: 'No significant whale movement in last 10 blocks' },
    ],
    selected: { worker: 'TrendAnalyzer-1', specialty: 'trend', score: 12.4 },
    direction: 'up',
    proof: {
      localHash: 'sha256:9f86d081884c7d65',
      hcsTopicId: '0.0.9039261',
      hcsTransactionId: '0.0.9038975@1717081200.123456789',
      mirrorNodeUrl: 'https://testnet.mirrornode.hedera.com',
    },
  },
  {
    id: 'evidence-1717080900456-y3b2',
    version: '1.0',
    createdAt: new Date(Date.now() - 300_000).toISOString(),
    taskHash: '5d41402abc4b2a76',
    decisionHash: 'b2c3d4e5f6a78901',
    domain: 'volatility',
    task: {
      description: 'Bollinger squeeze breakout — short-term volatility expansion expected',
      maxCostHbar: 0.05,
    },
    votes: [
      { worker: 'VolatilityPro-3', specialty: 'volatility', confidence: 0.71, score: 8.9, evidence: 'BB width at 6-week low, ATR compression suggests expansion' },
      { worker: 'RiskGuard-5', specialty: 'risk', confidence: 0.68, score: 7.5, evidence: 'Position sizing reduced to 0.5x due to low confidence environment' },
    ],
    selected: { worker: 'VolatilityPro-3', specialty: 'volatility', score: 8.9 },
    direction: 'down',
    proof: {
      localHash: 'sha256:e3b0c44298fc1c14',
      hcsTopicId: '0.0.9039261',
    },
  },
  {
    id: 'evidence-1717080600789-z1c4',
    version: '1.0',
    createdAt: new Date(Date.now() - 480_000).toISOString(),
    taskHash: '7d793037a076018f',
    decisionHash: 'c3d4e5f6a7b89012',
    domain: 'sentiment',
    task: {
      description: 'Social sentiment spike on Hedera governance proposal #47',
      maxCostHbar: 0.03,
    },
    votes: [
      { worker: 'SentimentAI-2', specialty: 'sentiment', confidence: 0.62, score: 5.1, evidence: 'Twitter/X sentiment +0.34 std dev above 7-day mean' },
      { worker: 'NewsBot-4', specialty: 'sentiment', confidence: 0.55, score: 4.2, evidence: '3 positive headlines in last 4 hours, no FUD detected' },
    ],
    selected: { worker: 'SentimentAI-2', specialty: 'sentiment', score: 5.1 },
    direction: 'up',
    proof: {
      localHash: 'sha256:5d41402abc4b2a76',
    },
  },
  {
    id: 'evidence-1717080300111-w8d5',
    version: '1.0',
    createdAt: new Date(Date.now() - 660_000).toISOString(),
    taskHash: '9e107d9d372bb682',
    decisionHash: 'd4e5f6a7b8c90123',
    domain: 'defi',
    task: {
      description: 'SaucerSwap TVL change implications for HBAR demand',
      maxCostHbar: 0.04,
    },
    votes: [
      { worker: 'DeFiAnalyst-6', specialty: 'defi', confidence: 0.77, score: 10.3, evidence: 'TVL +12% in 24h, yield farming APY compression suggests capital inflow' },
    ],
    selected: { worker: 'DeFiAnalyst-6', specialty: 'defi', score: 10.3 },
    direction: 'up',
    proof: {
      localHash: 'sha256:7d793037a076018f',
      hcsTopicId: '0.0.9039262',
      hcsTransactionId: '0.0.9038962@1717080300.987654321',
    },
  },
];

export const MOCK_SWARM_RECEIPT: SwarmReceipt = {
  version: '2.0.0',
  network: 'testnet',
  timestamp: Date.now() - 120_000,
  taskHash: 'e3b0c44298fc1c14',
  votes: [
    { workerId: 'vnx-trend-001', name: 'TrendAnalyzer-1', specialty: 'trend', confidence: 0.84, priceHbar: 0.01, score: 12.4 },
    { workerId: 'vnx-momentum-003', name: 'MomentumBot-3', specialty: 'momentum', confidence: 0.71, priceHbar: 0.008, score: 9.2 },
    { workerId: 'vnx-whale-007', name: 'WhaleWatcher-7', specialty: 'whale', confidence: 0.45, priceHbar: 0.005, score: 3.1 },
  ],
  selected: {
    workerId: 'vnx-trend-001',
    name: 'TrendAnalyzer-1',
    specialty: 'trend',
    priceHbar: 0.01,
    score: 12.4,
    confidence: 0.84,
    recommendation: 'up',
    evidence: 'EMA(12) crossed above EMA(26) with 2.3x volume confirmation',
  },
  payment: {
    status: 'skipped_plan_only',
    network: 'testnet',
    amountHbar: 0.01,
    recipient: '0.0.9038975',
  },
  proof: {
    voteHash: 'sha256:abcd1234efgh5678',
    receiptHash: 'sha256:9f86d081884c7d65',
    taskHash: 'e3b0c44298fc1c14',
  },
  decisionHash: 'a1b2c3d4e5f67890',
  proofStatus: 'not_mainnet_proof',
};

export const MOCK_REPLAY_RESULT: ReplayResult = {
  packetId: 'evidence-1717081200123-x7a9',
  originalTaskHash: 'e3b0c44298fc1c14',
  recomputedTaskHash: 'e3b0c44298fc1c14',
  originalDecisionHash: 'a1b2c3d4e5f67890',
  recomputedDecisionHash: 'a1b2c3d4e5f67890',
  taskHashMatch: true,
  decisionHashMatch: true,
  tampered: false,
  details: 'All hashes verified — packet is authentic',
};

export const MOCK_AGENT_STATUSES: AgentStatus[] = [
  { id: 'vnx-trend-001', name: 'TrendAnalyzer-1', specialty: 'trend', status: 'online', lastSeen: new Date().toISOString(), tasksCompleted: 142, accuracy: 0.78, hbarEarned: 1.42 },
  { id: 'vnx-momentum-003', name: 'MomentumBot-3', specialty: 'momentum', status: 'busy', lastSeen: new Date().toISOString(), tasksCompleted: 98, accuracy: 0.71, hbarEarned: 0.98 },
  { id: 'vnx-volatility-003', name: 'VolatilityPro-3', specialty: 'volatility', status: 'online', lastSeen: new Date(Date.now() - 30_000).toISOString(), tasksCompleted: 87, accuracy: 0.74, hbarEarned: 0.87 },
  { id: 'vnx-sentiment-002', name: 'SentimentAI-2', specialty: 'sentiment', status: 'online', lastSeen: new Date().toISOString(), tasksCompleted: 76, accuracy: 0.65, hbarEarned: 0.76 },
  { id: 'vnx-whale-007', name: 'WhaleWatcher-7', specialty: 'whale', status: 'degraded', lastSeen: new Date(Date.now() - 300_000).toISOString(), tasksCompleted: 54, accuracy: 0.58, hbarEarned: 0.54 },
  { id: 'vnx-risk-005', name: 'RiskGuard-5', specialty: 'risk', status: 'online', lastSeen: new Date().toISOString(), tasksCompleted: 112, accuracy: 0.82, hbarEarned: 1.12 },
  { id: 'vnx-defi-006', name: 'DeFiAnalyst-6', specialty: 'defi', status: 'offline', lastSeen: new Date(Date.now() - 600_000).toISOString(), tasksCompleted: 43, accuracy: 0.69, hbarEarned: 0.43 },
  { id: 'vnx-onchain-008', name: 'ChainMonitor-8', specialty: 'onchain', status: 'online', lastSeen: new Date().toISOString(), tasksCompleted: 201, accuracy: 0.85, hbarEarned: 2.01 },
];

export const MOCK_BITLATTICE_FLOW: BitLatticeFlow = {
  nodes: [
    { id: 'input', label: 'Signal Input', type: 'input', status: 'active', latencyMs: 0, throughput: 1000, description: 'Raw market signal ingestion' },
    { id: 'risk-prefilter', label: 'Risk Prefilter', type: 'decision', status: 'active', latencyMs: 0.05, throughput: 1000, description: 'Fast-path block/allow based on risk score threshold' },
    { id: 'ultra-router', label: 'Ultra Tier Router', type: 'process', status: 'active', latencyMs: 0.12, throughput: 850, description: 'Route to fast (ONNX) or deep (Nemotron) inference' },
    { id: 'onnx-fast', label: 'ONNX Fast Path', type: 'process', status: 'active', latencyMs: 0.014, throughput: 700, description: 'Quantized ONNX inference (85μs→14μs)' },
    { id: 'nemotron-deep', label: 'Nemotron Deep', type: 'process', status: 'idle', latencyMs: 450, throughput: 150, description: 'LLM reasoning with rationale generation' },
    { id: 'ensemble', label: 'Ensemble Voter', type: 'decision', status: 'active', latencyMs: 0.08, throughput: 700, description: 'Weighted multi-model consensus aggregation' },
    { id: 'quality-gate', label: 'Quality Gate', type: 'decision', status: 'active', latencyMs: 0.06, throughput: 700, description: 'Confidence and evidence quality validation' },
    { id: 'hcs-publisher', label: 'HCS Publisher', type: 'process', status: 'active', latencyMs: 120, throughput: 550, description: 'Compact HCS message publish to Hedera' },
    { id: 'edge-node', label: 'Edge Swarm Node', type: 'output', status: 'active', latencyMs: 45, throughput: 300, description: 'Distributed edge execution and relay' },
    { id: 'output', label: 'Decision Output', type: 'output', status: 'active', latencyMs: 0, throughput: 700, description: 'Final allow/block/size_down/ask_swarm' },
  ],
  edges: [
    { from: 'input', to: 'risk-prefilter', label: 'signal', active: true },
    { from: 'risk-prefilter', to: 'ultra-router', label: 'allow', active: true },
    { from: 'risk-prefilter', to: 'output', label: 'block', active: false },
    { from: 'ultra-router', to: 'onnx-fast', label: 'fast', active: true },
    { from: 'ultra-router', to: 'nemotron-deep', label: 'deep', active: false },
    { from: 'onnx-fast', to: 'ensemble', label: 'prediction', active: true },
    { from: 'nemotron-deep', to: 'ensemble', label: 'rationale', active: false },
    { from: 'ensemble', to: 'quality-gate', label: 'consensus', active: true },
    { from: 'quality-gate', to: 'hcs-publisher', label: 'pass', active: true },
    { from: 'quality-gate', to: 'output', label: 'fail', active: false },
    { from: 'hcs-publisher', to: 'edge-node', label: 'broadcast', active: true },
    { from: 'edge-node', to: 'output', label: 'relay', active: true },
  ],
  currentPacket: {
    packetId: 'fast:1717081200000:42',
    symbol: 'HBAR/USD',
    baselineDecision: 'allow',
    riskScore: 0.24,
    confidence: 0.84,
  },
};
